- project:
    name: project-example
    views:
       - view:
           name: kgordey
           view-type: list
           description: 'description'
           columns:
             - status
             - weather
             - job
             - last-success
             - last-failure
             - last-duration
    jobs:
       - 'MNTLAB_{name}_child{number}_job':
           name: kgordey
           number: 1
           command: ls
       - 'MNTLAB_{name}_child{number}_job':
           name: kgordey
           number: 2
           command: ls
       - 'MNTLAB_{name}_child{number}_job':
           name: kgordey
           number: 3
           command: ls
       - 'MNTLAB_{name}_child{number}_job':
           name: kgordey
           number: 4
           command: ls
       - 'MNTLAB_{name}_master_job':
           name: kgordey
